# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: Apache-2.0

---

name: "Nomad JWT Auth"
author: "Mike Nomitch"
description: "A GitHub Action to mint a short-lived Nomad token using GHA identity tokens"
inputs:
  url:
    description: "The URL of the Nomad cluster"
    required: true
  methodName:
    description: "The name of the Nomad Auth Method to use"
    default: "github"
    required: false
  identityToken:
    description: "The JWT identity token to use. Will use Github Action if not provided"
    required: false
  jwtGithubAudience:
    description: "The audience to use for the Github Action identity token. Only used if JWT not provided and using GHA JWT"
    required: false
  exportToken:
    description: 'Whether or not export Nomad token as environment variables'
    default: 'true'
    required: false
  outputToken:
    description: 'Whether or not to set the `nomadToken` output to contain the Nomad token after authentication'
    default: 'true'
    required: false
  tlsSkipVerify:
    default: 'false'
    description: "When set to true, disables verification of the Nomad server certificate - setting this to true in production is not recommended"
    required: false
  caCertificate:
    description: "Base64 encoded CA certificate to verify the Nomad server certificate"
    required: false
  clientCertificate:
    description: "Base64 encoded client certificate for mTLS communication with the Nomad server"
    required: false
  clientKey:
    description: "Base64 encoded client key for mTLS communication with the Nomad server"
    required: false
  extraHeaders:
    description: "A string of newline separated extra headers to include on every request"
    required: false
outputs:
  nomad_token:
    description: "The Nomad token minted using github auth"
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: "terminal"
  color: "green"
